### ISSUE TITLE
X chromsome issue with reference

### ISSUE THREAD

**Issue by stefpiatek** [VUmcCGP/wisexome#5]
I have an error when I follow the README instructions where the takeref.py script can't find the X chromosome reference

```
 python2.7 takeref.py /mnt/output/ICR/wisexome/BRCA1/prepref /mnt/output/ICR/wisexome/BRCA1/takeref/refname

Traceback (most recent call last):
  File "takeref.py", line 46, in <module>
    newData = cPickle.load(open(refData + '/' + str(tChrom) + '.' + str(rChrom) + '.ref','r'))
IOError: [Errno 2] No such file or directory: '/mnt/output/ICR/wisexome/BRCA1/prepref/X.1.ref'
```
Yet if I try to run the prepref.py with the autosomes and X chromosome I get this error (it works with the autosomes however, as stated in the README):

```
python2.7 prepref.py /mnt/output/ICR/wisexome/BRCA1/lennormalize/normal/ /mnt/output/ICR/wisexome/BRCA1/prepref/X.1.ref chrX chr1


Traceback (most recent call last):
  File "prepref.py", line 86, in <module>
    print len(tarsT),len(tarsT[0])
IndexError: list index out of range
```

Seems like an issue where maybe this tool should only call on autosomes or am I doing something wrong?

**Comment by rstraver** [comment]
Hi Stef, sorry for the slow response. If you just want to run this tool without X I think your best bet is commenting line 39 in prepref.py:
`#tChroms.append('X')`

Adding the X chromosome was a bit of an afterthought and it shows throughout the code.
There are probably several more not-so-nice leftovers from some experiments, so there may be some more issues here and there...

**Comment by nayoung9** [comment]
> Hi Stef, sorry for the slow response. If you just want to run this tool without X I think your best bet is commenting line 39 in prepref.py:
> `#tChroms.append('X')`
> 
> Adding the X chromosome was a bit of an afterthought and it shows throughout the code.
> There are probably several more not-so-nice leftovers from some experiments, so there may be some more issues here and there...

Hi.
I have the exact same error, therefore I ran left processes without X chromosome. 
And they ran seems well. 
However, I cannot find the true result. 
What I've got in 'testout' directory are pickle files for every sample for every chromosome. Also, there was only string ".(lp0" in almost every .pickle
I didn't get any error messages to catch up any fault in processes. What should I do with this tool ?
